//   NOTE: this is a machine generated file--editing not recommended
//
// storage_notify_pkt.h - class definitions for ASN.1 module MIBONOTIFY
//
//   This file was generated by snacc on Mon Dec  7 20:53:47 2009
//   UBC snacc by Mike Sample
//   A couple of enhancements made by IBM European Networking Center

#ifndef _storage_notify_pkt_h_
#define _storage_notify_pkt_h_


//------------------------------------------------------------------------------
// class declarations:

namespace fuck {

class ReqNotify;

//------------------------------------------------------------------------------
// class definitions:

class ReqNotify: public AsnType
{
public:
  AsnInt		needrsp;
  AsnOcts		proto;
  AsnOcts		reqblob;
  AsnInt		resv1;
  AsnOcts		resv2;

			ReqNotify();
			ReqNotify (const ReqNotify &);
			~ReqNotify();
  AsnType		*Clone() const;

  ReqNotify		&operator = (const ReqNotify &);
  AsnLen		BEncContent (BUF_TYPE b);
  void			BDecContent (BUF_TYPE b, AsnTag tag, AsnLen elmtLen, AsnLen &bytesDecoded, ENV_TYPE env);

  AsnLen		BEnc (BUF_TYPE b);
  void			BDec (BUF_TYPE b, AsnLen &bytesDecoded, ENV_TYPE env);
  int			BEncPdu (BUF_TYPE b, AsnLen &bytesEncoded);
  int			BDecPdu (BUF_TYPE b, AsnLen &bytesDecoded);

  void		Print (ostream &os) const;
};


//------------------------------------------------------------------------------
// externs for value defs

//------------------------------------------------------------------------------
}/* end of namespace fuck */


#endif /* conditional include of storage_notify_pkt.h */
